### PR TITLE
Update: pull in upstream changes

### PR DESCRIPTION
**Pull request by SlySven**
This PR cherry-picks all the commits made upstream and then merges in that upstream with the result that they have identical code.  {*Edit: that may not have been the optimum as it seems that each non-merge commit appears twice!*}

It should be possible to consider switching to the upstream repository which would make some third parties (packagers) happy as they could consider dropping our fork and using upstream for their builds. OTOH if upstream make changes that we are not happy with (or we want to make changes that upstream don't want) then keeping a parallel repository makes sense - however we really must keep ours in step with upstream if we want to tell third parties "you can use either"...

### CODE REVIEW

**Comment by SlySven** [comment]
The CI stuff is completely borked at present - it is still using the Ubutu Trusty distribution and is using Qt 5.6 ... it needs an update IMHO as that part was last revised in 2017...

... FTR it is our CI stuff BTW, upstream does not seem to make use of it.

This is intended to be used for the replacement for https://github.com/Mudlet/Mudlet/pull/4198 .

**Comment by vadi2** [comment]
Hm, but we don't want to be able to tell others that they can use either - they need to use what we use.

**Review by vadi2 — APPROVED** [review]

**Comment by vadi2** [comment]
Hm, on second thought, why cherrypick all commits? Right now we don't have any specific changes, we merged everything into upstream - this means that we can just fast-forward the branch:

image

**Comment by SlySven** [comment]
Closing in favour of #7

**Pull request closed without merging**
